"""empty message

Revision ID: 1a3e7b351c87
Revises: e7e2ddc36307
Create Date: 2026-03-15 15:00:48.336057

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1a3e7b351c87'
down_revision: Union[str, Sequence[str], None] = 'e7e2ddc36307'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users_table',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.alter_column('expenses_table', 'event_date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('expenses_table', 'expense_date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.create_foreign_key(None, 'expenses_table', 'users_table', ['user_id'], ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'expenses_table', type_='foreignkey')
    op.alter_column('expenses_table', 'expense_date',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('expenses_table', 'event_date',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.drop_table('users_table')
    # ### end Alembic commands ###
