"""empty message

Revision ID: e7e2ddc36307
Revises: 
Create Date: 2026-03-15 11:08:03.875815

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7e2ddc36307'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('expenses_table',
    sa.Column('expense_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('expense_value', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('event_date', sa.DateTime(), nullable=False),
    sa.Column('expense_date', sa.DateTime(), nullable=True),
    sa.Column('expense_category', sa.String(length=50), nullable=True),
    sa.Column('expense_desc', sa.String(length=300), nullable=True),
    sa.PrimaryKeyConstraint('expense_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('expenses_table')
    # ### end Alembic commands ###
