version: '3.8'

services:
  db:
    image: postgres:16 
    restart: always
    environment:
      POSTGRES_PASSWORD: supersecretpass
      POSTGRES_USER: finance_squirrel 
      POSTGRES_DB: finance_squirrel_db 
    ports:
      - "5432:5432" 
    volumes:
      - postgres_data:/var/lib/postgresql/data 

volumes:
  postgres_data:

